### ISSUE TITLE
Readme file, statement regarding deltaT parameter

### ISSUE THREAD

**Issue by pcharest2000** [leomil72/swRTC#2]
In the readme file you state:

 If your RTC is faster than the real time, try adjusting deltaT with positive values, if your RTC is slower, try a deltaT with a negative values.

I looked at the implementation and did some test (not extensive) I beleive it is the opposite around,  with a positive delta you are incrementing CounterT thus making the time faster...  and the opposite for negative values.    This implementation is intuitive   can yo verify I am wrong.

Also I have modified the code so it can run on a 20Mhz crystal (on AttinyX4  at the same multiplier as per 16Mhz.   How do I submit this code I am new to GIT.

By the way great work, I am using your library (wiouth arduino) for a VFD clock) 

Phil

**Comment by leomil72** [comment]
You're right. Your issue also lead me to find another bug into the code. Thanks.
