### ISSUE TITLE
add esp8266 and esp32 implementation

### ISSUE THREAD

**Issue by EngrMubasharAli** [leomil72/swRTC#8]
kindly add support for esp8266 and esp32 and other controllers like STM

**Comment by leomil72** [comment]
The lib has been written to work on Atmel AVR MCUs, to provide for them a clock support; at the moment I don't have time and/or knowledge to port it to other platforms. Sorry.

**Comment by zoomx** [comment]
The esp8266 and, maybe, the ESP32, has his own functions builtin in the core and there is also a NTP synchronisation. 
See the NTP-TZ-DST example. The NTPclient example doesn't uses the builtin function.
